"""
Utah Public Infrastructure District Financial Model
====================================================

The Tierra Colorado metropolitan district model (``co_metro_model``), rebuilt
for Utah public infrastructure districts organised under the Public
Infrastructure District Act, Title 17D, Chapter 4, Utah Code.  Same module
layout, same sheet dependency order, same outputs — with Utah's property tax
framework in place of Colorado's.

Sheet dependency order (bottom-up):

  Inputs (config)
  Residential / Commercial Development       →  development.py
  Summary (taxable value & pledged revenue)  →  summary.py
  Senior Lien DS  (revenue-wrap sizing)      →  debt_service.py
  Subordinate Lien DS (cash-flow waterfall)  →  subordinate.py
  Sources & Uses + Reimbursement             →  sources_uses.py
  Refunding (refinance senior new-money)     →  refunding.py
  Multi-sheet Excel report                   →  report.py

The headline outputs are the developer **reimbursement** from the first
financing and the **additional reimbursement ("new money")** generated by
refinancing the senior new-money bonds.

See ``docs/utah-vs-colorado.md`` for every substantive difference and where it
lands in the code.
"""

from .config import ModelConfig
from .config import (PID_STATUTORY_LEVY_CAP, RESIDENTIAL_EXEMPTION,
                     UTAH_TAX_CALENDAR, lot_inventory_ratio,
                     residential_taxable_ratio_for)
from .development import (DeveloperProjections, ProductLine,
                          viridian_farm_projections)
from .summary import SummaryModel
from .debt_service import (
    SeniorLienSizer, BondTranche, CallProvisions, schedule_dataframe,
    senior_coverage_schedule, senior_coverage_dataframe,
    standard_dsrf, size_senior_with_dynamic_dsrf,
)
from .subordinate import SubordinateLien, SurplusFund
from .sources_uses import SourcesUses, first_financing_sources_uses
from .refunding import RefundingAnalysis, RefundingResult
from .report import build_excel_report
from .forecast_report import build_forecast_report
from .scenarios import Scenario, build_scenarios
from .inputs import write_inputs_workbook, load_inputs_workbook
from .memo import build_memo_html

__all__ = [
    "ModelConfig",
    "PID_STATUTORY_LEVY_CAP",
    "RESIDENTIAL_EXEMPTION",
    "UTAH_TAX_CALENDAR",
    "residential_taxable_ratio_for",
    "lot_inventory_ratio",
    "viridian_farm_projections",
    "DeveloperProjections",
    "ProductLine",
    "SummaryModel",
    "SeniorLienSizer",
    "BondTranche",
    "CallProvisions",
    "schedule_dataframe",
    "senior_coverage_schedule",
    "senior_coverage_dataframe",
    "standard_dsrf",
    "size_senior_with_dynamic_dsrf",
    "SubordinateLien",
    "SurplusFund",
    "SourcesUses",
    "first_financing_sources_uses",
    "RefundingAnalysis",
    "RefundingResult",
    "build_excel_report",
    "build_forecast_report",
    "Scenario",
    "build_scenarios",
    "write_inputs_workbook",
    "build_memo_html",
    "load_inputs_workbook",
]
